apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: commx-prod
  labels:
    app: redis
    owner: group-1
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: commx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
