apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: commx-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine # Langsung pakai official image
        # Tambahan config: Mengaktifkan password dan mengaktifkan persistence AOF
        command: ["redis-server", "--requirepass", "redispassgacor", "--appendonly", "yes"]
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-storage
          mountPath: /data
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: commx-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: commx-prod
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
