---
- name: Cek helm sudah terpasang
  ansible.builtin.command: helm version --short
  register: helm_check
  changed_when: false
  failed_when: false

- name: Install Helm
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    executable: /bin/bash
    creates: /usr/local/bin/helm
  when: helm_check.rc != 0
