apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: commx-prod
  labels:
    app: frontend
    owner: group-1
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: commx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
