apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: commx-prod
  labels:
    app: backend
    owner: group-1
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: commx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
