apiVersion: v1
kind: ConfigMap
metadata:
  name: commx-config
  namespace: commx-prod
  labels:
    app: commx
    owner: group-1
    app.kubernetes.io/name: commx-config
    app.kubernetes.io/part-of: commx
data:
  NODE_ENV: "production"
  PORT: "3000"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
